# Generated by Django 2.1.1 on 2018-10-03 22:20

from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import mastermind.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peg1', enumchoicefield.fields.EnumChoiceField(default=mastermind.models.Color(2), enum_class=mastermind.models.Color, max_length=7)),
                ('peg2', enumchoicefield.fields.EnumChoiceField(default=mastermind.models.Color(2), enum_class=mastermind.models.Color, max_length=7)),
                ('peg3', enumchoicefield.fields.EnumChoiceField(default=mastermind.models.Color(2), enum_class=mastermind.models.Color, max_length=7)),
                ('peg4', enumchoicefield.fields.EnumChoiceField(default=mastermind.models.Color(2), enum_class=mastermind.models.Color, max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='AttemptResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response1', enumchoicefield.fields.EnumChoiceField(blank=True, enum_class=mastermind.models.ResultColor, max_length=5, null=True)),
                ('response2', enumchoicefield.fields.EnumChoiceField(blank=True, enum_class=mastermind.models.ResultColor, max_length=5, null=True)),
                ('response3', enumchoicefield.fields.EnumChoiceField(blank=True, enum_class=mastermind.models.ResultColor, max_length=5, null=True)),
                ('response4', enumchoicefield.fields.EnumChoiceField(blank=True, enum_class=mastermind.models.ResultColor, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peg1', enumchoicefield.fields.EnumChoiceField(default=mastermind.models.Color(2), enum_class=mastermind.models.Color, max_length=7)),
                ('peg2', enumchoicefield.fields.EnumChoiceField(default=mastermind.models.Color(2), enum_class=mastermind.models.Color, max_length=7)),
                ('peg3', enumchoicefield.fields.EnumChoiceField(default=mastermind.models.Color(2), enum_class=mastermind.models.Color, max_length=7)),
                ('peg4', enumchoicefield.fields.EnumChoiceField(default=mastermind.models.Color(2), enum_class=mastermind.models.Color, max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastermind.Game'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='result',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mastermind.AttemptResponse'),
        ),
    ]
